version: "3.7"
services:
  jogodistribuido_app1:
    #    image: timbeck1997/jogodistribuido:latest
    image: jogodistribuido
    container_name: jogodistribuido_8080
    build: ./
    restart: always
    ports:
      - "8080:8080"
    networks:
      - jogodistribuido_network
    environment:
      - SERVER_PORT=8080
      - APP_NAME=app0(8080)
      - DATABASE_HOST=database_postgres

  jogodistribuido_app2:
    #    image: timbeck1997/jogodistribuido:latest
    image: jogodistribuido
    container_name: jogodistribuido_8081
    build: .
    restart: always
    ports:
      - "8081:8081"
    networks:
      - jogodistribuido_network
    environment:
      - SERVER_PORT=8081
      - APP_NAME=app1(8081)
      - DATABASE_HOST=database_postgres

  jogodistribuido_app3:
#    image: timbeck1997/jogodistribuido:latest
    image: jogodistribuido
    container_name: jogodistribuido_8082
    build: .
    restart: always
    ports:
      - "8082:8082"
    networks:
      - jogodistribuido_network
    environment:
      - SERVER_PORT=8082
      - APP_NAME=app2(8082)
      - DATABASE_HOST=database_postgres
  database_postgres:
    container_name: database_postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jogodistribuido
    networks:
      - jogodistribuido_network

  webserver:
    image: "nginx"
    container_name: container-nginx
    ports:
      - "9090:9090"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      jogodistribuido_network:
    depends_on:
      - "jogodistribuido_app1"
      - "jogodistribuido_app2"
      - "jogodistribuido_app3"
#  webserver:
#    image: haproxy:2.3
#    restart: always
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./haproxy:/usr/local/etc/haproxy
#      - "./haproxy/cors.lua:/etc/haproxy/cors.lua"
#    networks:
#      - jogodistribuido_network

networks:
  jogodistribuido_network:
    driver: bridge
