

name: Deploy projeto no dockerhub

on:
  push:
    branches: 
      - master
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Application with Maven
      run: mvn clean package
      
      working-directory: backend/
      
    - name: Docker Compose Build
      working-directory: backend/
      run: docker compose build
      
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: timbeck1997/jogodistribuido:latest, timbeck1997/jogodistribuido:${{ github.run_number}}
   
